### ISSUE TITLE
Documentation dependency issue

### ISSUE THREAD

**Issue by DenninDalke** [red-owl-games/UIEX#2]
In the documentation:
https://redowlgames.com/UIEX/installation.html

it states that you should use ` "com.redowl.editor.uiex": "https://github.com/red-owl-games/UIEX.git"` but the package isn't using this name anymore, which gives this issue:

```An error occurred while resolving packages:
  Project has invalid dependencies:
    com.redowl.editor.uiex: The requested dependency 'com.redowl.editor.uiex' does not match the `name` 'com.redowl.uiex' specified in the package manifest of [com.redowl.editor.uiex@https://github.com/red-owl-games/UIEX.git]

A re-import of the project may be required to fix the issue or a manual modification of .../Packages/manifest.json file.
```

I've created a PR fixing the issue: https://github.com/red-owl-games/UIEX/pull/1

**Comment by rocktavious** [comment]
Thanks for that @DenninDalke good catch
