### ISSUE TITLE
About  HandleUXMLReferenceAttributes

### ISSUE THREAD

**Issue by chaoslife** [red-owl-games/UIEX#3]
Hello, I have newly created a new window, inherits RedOwlEditorWindow, adds a field IntegerSlider to the Class, and uses [UXMLReference].
Found in the RedOwlUtils.HandleUXMLReferenceAttributes method, info.SetValue(instance, element.Q(uxmlName));, the value of element.Q(uxmlName) is null. Is there any related example?

**Comment by rocktavious** [comment]
@chaoslife Did you figure this out?  If not i can still help - Can you post an example of your code?

**Comment by chaoslife** [comment]
Thanks for the reply, I have solved this problem. I didn't find the uxml file name with the Layout suffix at first, and then solved it.

**Comment by rocktavious** [comment]
@chaoslife ahh ya i added suffixes - great its working out for you - if you think there is anything in the docs i could make clearer let me know.  I don't develop on this project full time and the UIElements is still in flux alot but i think there is alot of merit to the boilerplate this repo takes care of so if you can think of anything else please let me know!  Thanks for using it
