### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by IbakonFerba** [red-owl-games/UIEX#6]
I want to try out Sleipnir, which is dependant on this package, but when I try to install the package via the package manager Unity tells me that this is not a valid package repository.

This is the error: Cannot perform upm operation: Unable to add package [https://github.com/red-owl-games/UIEX.git]:
  [https://github.com/red-owl-games/UIEX.git] does not point to a valid package repository. No package manifest was found. Verify the repository URL and make sure the package is located in the root folder of the repository. [NotFound]

**Comment by IbakonFerba** [comment]
I created a pull request with the solution

**Comment by rocktavious** [comment]
closed by #7
